"""enforce cohort and team integrity

Revision ID: 062e3c6453f4
Revises: 5a8474eba8d7
Create Date: 2026-09-26 15:55:20.257025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062e3c6453f4'
down_revision: Union[str, Sequence[str], None] = '5a8474eba8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_enrollment_per_user', 'enrollments', ['user_id'], unique=True, postgresql_where=sa.text("enrollment_status = 'active'"))
    op.create_index('uq_team_single_lead', 'team_memberships', ['team_id'], unique=True, postgresql_where=sa.text("team_role = 'lead'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_team_single_lead', table_name='team_memberships', postgresql_where=sa.text("team_role = 'lead'"))
    op.drop_index('uq_active_enrollment_per_user', table_name='enrollments', postgresql_where=sa.text("enrollment_status = 'active'"))
    # ### end Alembic commands ###
