"""add session scoped resources

Revision ID: 0918fe528c91
Revises: 0a8152b242b0
Create Date: 2026-09-28 10:02:21.958297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0918fe528c91'
down_revision: Union[str, Sequence[str], None] = '0a8152b242b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_resources_session_id'), 'resources', ['session_id'], unique=False)
    op.create_foreign_key(
        "fk_resources_session_id_sessions",
        "resources",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_resources_session_id_sessions",
        "resources",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_resources_session_id'), table_name='resources')
    op.drop_column('resources', 'session_id')
    # ### end Alembic commands ###
