"""add session unlock submission and transcript fields

Revision ID: 585947a40df9
Revises: 062e3c6453f4
Create Date: 2026-09-26 18:30:31.301131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585947a40df9'
down_revision: Union[str, Sequence[str], None] = '062e3c6453f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "sessions",
        sa.Column(
            "unlock_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "sessions",
        sa.Column(
            "submission_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )

    op.add_column(
        "sessions",
        sa.Column(
            "transcript_url",
            sa.String(length=500),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_sessions_unlock_at"),
        "sessions",
        ["unlock_at"],
        unique=False,
    )

    # Existing rollout rule:
    # Sessions 0, 1 and 2 are immediately available.
    # Session 3+ unlock at their scheduled start time.
    op.execute(
        """
        UPDATE sessions
        SET unlock_at =
            CASE
                WHEN session_number <= 2 THEN NOW()
                ELSE start_at
            END
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_unlock_at'), table_name='sessions')
    op.drop_column('sessions', 'transcript_url')
    op.drop_column('sessions', 'submission_enabled')
    op.drop_column('sessions', 'unlock_at')
    # ### end Alembic commands ###
