"""add google calendar fields to sessions

Revision ID: 5a8474eba8d7
Revises: 7317057261fe
Create Date: 2026-09-25 22:53:22.881837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8474eba8d7'
down_revision: Union[str, Sequence[str], None] = '7317057261fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('google_calendar_event_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'google_calendar_event_url')
    op.drop_column('sessions', 'google_calendar_event_id')
    # ### end Alembic commands ###
