"""add team submissions

Revision ID: 71b64ccfae91
Revises: 0918fe528c91
Create Date: 2026-09-28 11:11:51.831233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b64ccfae91'
down_revision: Union[str, Sequence[str], None] = '0918fe528c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('drive_url', sa.String(length=1000), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'team_id', name='uq_session_team_submission')
    )
    op.create_index(op.f('ix_team_submissions_session_id'), 'team_submissions', ['session_id'], unique=False)
    op.create_index(op.f('ix_team_submissions_submitted_by_user_id'), 'team_submissions', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_team_submissions_team_id'), 'team_submissions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_submissions_team_id'), table_name='team_submissions')
    op.drop_index(op.f('ix_team_submissions_submitted_by_user_id'), table_name='team_submissions')
    op.drop_index(op.f('ix_team_submissions_session_id'), table_name='team_submissions')
    op.drop_table('team_submissions')
    # ### end Alembic commands ###
