"""make session schedule optional and add google meet fields

Revision ID: 7317057261fe
Revises: d8d74f01eeac
Create Date: 2026-09-25 15:33:12.756382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7317057261fe'
down_revision: Union[str, Sequence[str], None] = 'd8d74f01eeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('meeting_provider', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('google_meet_space_name', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('google_meet_code', sa.String(length=100), nullable=True))
    op.alter_column('sessions', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('sessions', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'end_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sessions', 'start_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('sessions', 'google_meet_code')
    op.drop_column('sessions', 'google_meet_space_name')
    op.drop_column('sessions', 'meeting_provider')
    # ### end Alembic commands ###
