"""add team company challenge resources

Revision ID: bf3f9d75fe33
Revises: d847d5a123bf
Create Date: 2026-09-29 16:13:26.012428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3f9d75fe33'
down_revision: Union[str, Sequence[str], None] = 'd847d5a123bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_challenge_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_challenge_resources_team_id'), 'team_challenge_resources', ['team_id'], unique=False)
    op.add_column('teams', sa.Column('company_overview', sa.String(length=3000), nullable=True))
    op.add_column('teams', sa.Column('challenge_description', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'challenge_description')
    op.drop_column('teams', 'company_overview')
    op.drop_index(op.f('ix_team_challenge_resources_team_id'), table_name='team_challenge_resources')
    op.drop_table('team_challenge_resources')
    # ### end Alembic commands ###
