"""add program cohort discover structure

Revision ID: c3598e52c02b
Revises: d51e7399a0ff
Create Date: 2026-09-25 12:41:29.677961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3598e52c02b'
down_revision: Union[str, Sequence[str], None] = 'd51e7399a0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_table('cohorts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'upcoming', 'active', 'completed', 'archived', name='cohort_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_code'), 'cohorts', ['code'], unique=True)
    op.create_index(op.f('ix_cohorts_program_id'), 'cohorts', ['program_id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('development_role', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'code', name='uq_program_phase_code'),
    sa.UniqueConstraint('program_id', 'sequence', name='uq_program_phase_sequence')
    )
    op.create_index(op.f('ix_phases_program_id'), 'phases', ['program_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_status', sa.Enum('invited', 'active', 'completed', 'withdrawn', name='enrollment_status'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cohort_id', name='uq_user_cohort_enrollment')
    )
    op.create_index(op.f('ix_enrollments_cohort_id'), 'enrollments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('weeks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('strategic_question', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('unlock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'sequence', name='uq_phase_week_sequence'),
    sa.UniqueConstraint('phase_id', 'week_number', name='uq_phase_week_number')
    )
    op.create_index(op.f('ix_weeks_phase_id'), 'weeks', ['phase_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('week_id', sa.UUID(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('induction', 'learn_work', 'output_review', name='session_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'completed', 'cancelled', name='session_status'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'sequence', name='uq_cohort_session_sequence'),
    sa.UniqueConstraint('cohort_id', 'session_number', name='uq_cohort_session_number')
    )
    op.create_index(op.f('ix_sessions_cohort_id'), 'sessions', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_sessions_phase_id'), 'sessions', ['phase_id'], unique=False)
    op.create_index(op.f('ix_sessions_start_at'), 'sessions', ['start_at'], unique=False)
    op.create_index(op.f('ix_sessions_week_id'), 'sessions', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_week_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_start_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_phase_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_cohort_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_weeks_phase_id'), table_name='weeks')
    op.drop_table('weeks')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_cohort_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_phases_program_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_cohorts_program_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_code'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
