"""add_totp_secret_and_recovery_codes

Revision ID: c43f0e383efd
Revises: a21e634726cc
Create Date: 2026-09-25 09:59:16.603824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43f0e383efd'
down_revision: Union[str, Sequence[str], None] = 'a21e634726cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recovery_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recovery_codes_code_hash'), 'user_recovery_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_user_recovery_codes_user_id'), 'user_recovery_codes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    op.drop_index(op.f('ix_user_recovery_codes_user_id'), table_name='user_recovery_codes')
    op.drop_index(op.f('ix_user_recovery_codes_code_hash'), table_name='user_recovery_codes')
    op.drop_table('user_recovery_codes')
    # ### end Alembic commands ###
