"""add submission feedback

Revision ID: d847d5a123bf
Revises: 71b64ccfae91
Create Date: 2026-09-28 12:27:23.169203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd847d5a123bf'
down_revision: Union[str, Sequence[str], None] = '71b64ccfae91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('feedback_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['team_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_submission_feedback_submission')
    )
    op.create_index(op.f('ix_submission_feedback_reviewed_by_user_id'), 'submission_feedback', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_submission_feedback_submission_id'), 'submission_feedback', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_feedback_submission_id'), table_name='submission_feedback')
    op.drop_index(op.f('ix_submission_feedback_reviewed_by_user_id'), table_name='submission_feedback')
    op.drop_table('submission_feedback')
    # ### end Alembic commands ###
